# Generated by Django 4.1 on 2023-04-09 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GlycoOnto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('function', models.CharField(max_length=100)),
                ('sub_function', models.CharField(max_length=100)),
                ('sub_sub_function', models.CharField(max_length=100)),
                ('sub_sub_sub_function', models.CharField(max_length=100)),
                ('pathway', models.CharField(max_length=100)),
                ('sub_pathway', models.CharField(max_length=100)),
                ('sub_sub_pathway', models.CharField(max_length=100)),
                ('sub_sub_sub_pathway', models.CharField(max_length=100)),
                ('gene_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'glycodb',
                'managed': False,
            },
        ),
    ]
